// Package compiler compiles
package compiler

import (
	"Goauld/common/log"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Artifact holds the artifact struct generated by the goreleaser command.
type Artifact struct {
	Name         string `json:"name"`
	Path         string `json:"path"`
	InternalType int    `json:"internal_type"`
	Type         string `json:"type"`
	Goos         string `json:"goos,omitempty"`
	Goarch       string `json:"goarch,omitempty"`
	Goamd64      string `json:"goamd64,omitempty"`
	Target       string `json:"target,omitempty"`
	Extra        struct {
		Binary    string   `json:"Binary,omitempty"`
		Builder   string   `json:"Builder,omitempty"`
		Ext       string   `json:"Ext,omitempty"`
		ID        string   `json:"ID,omitempty"`
		Binaries  []string `json:"Binaries,omitempty"`
		Checksum  string   `json:"Checksum,omitempty"`
		Format    string   `json:"Format,omitempty"`
		Replaces  any      `json:"Replaces"`
		WrappedIn string   `json:"WrappedIn,omitempty"`
	} `json:"extra,omitempty"`
	Go386   string `json:"go386,omitempty"`
	Goarm   string `json:"goarm,omitempty"`
	Goarm64 string `json:"goarm64,omitempty"`
}

// ParseArtifacts parses the artifact file and returns the corresponding struct.
func ParseArtifacts(filePath string) ([]Artifact, error) {
	// Open the JSON file
	//nolint:gosec
	file, err := os.Open(filePath)
	if err != nil {
		return nil, fmt.Errorf("error opening file: %w", err)
	}
	//nolint:errcheck
	defer file.Close()

	// Read the file's content
	data, err := io.ReadAll(file)
	if err != nil {
		return nil, fmt.Errorf("error reading file: %w", err)
	}

	// Unmarshal the JSON data into the XXX struct
	var result []Artifact
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, fmt.Errorf("error unmarshaling JSON: %w", err)
	}

	// Return the unmarshalled struct
	return result, nil
}

// MoveArtifacts moves the compiled artifacts to the destination folder.
func MoveArtifacts(artifacts []Artifact, source string, output string) error {
	for _, artifact := range artifacts {
		if artifact.Type == "Metadata" || artifact.Type == "Checksum" || artifact.Type == "Archive" {
			continue
		}
		outDir := filepath.Join(output, artifact.Extra.ID)
		err := MkdirAll(outDir)
		if err != nil {
			return fmt.Errorf("error creating dir: %w", err)
		}
		file := filepath.Join(source, artifact.Path)
		fatFile := file + ".fat"
		upx := true
		if _, err := os.Stat(fatFile); errors.Is(err, os.ErrNotExist) {
			upx = false
		}

		upxFailed, err := isFileSameSize(file, fatFile)

		if upx && !upxFailed && err == nil {
			// default file is compressed
			outFile := fmt.Sprintf("%s_%s-%s_%s%s", artifact.Extra.Binary, artifact.Goos, artifact.Goarch, "compressed", artifact.Extra.Ext)
			outPath := filepath.Join(outDir, outFile)
			err = CopyFile(file, outPath)
			if err != nil {
				return fmt.Errorf("error copying files: %w", err)
			}
			log.Info().Str("Source", file).Str("Dest", outPath).Msg("moved artifact")
			if artifact.Extra.Ext == ".dll" {
				dllHeaderOutFile := fmt.Sprintf("%s_%s-%s_%s%s", artifact.Extra.Binary, artifact.Goos, artifact.Goarch, "compressed", ".h")
				dllHeaderOutPath := filepath.Join(outDir, dllHeaderOutFile)
				headerFile := strings.TrimSuffix(file, ".dll") + ".h"
				err = CopyFile(headerFile, dllHeaderOutPath)
				if err != nil {
					return fmt.Errorf("error copying header files: %w", err)
				}
				log.Info().Str("Source", file).Str("Dest", dllHeaderOutPath).Msg("moved header artifact")
				dllOutFile := fmt.Sprintf("%s_%s-%s%s", artifact.Extra.Binary, artifact.Goos, artifact.Goarch, ".h")
				dllOutPath := filepath.Join(outDir, dllOutFile)
				headerFileRaw := strings.TrimSuffix(file, ".dll") + ".h"
				err = CopyFile(headerFileRaw, dllOutPath)
				if err != nil {
					return fmt.Errorf("error copying header files: %w", err)
				}
				log.Info().Str("Source", file).Str("Dest", dllOutPath).Msg("moved header artifact")
			}
			// .fat file is not compressed
			outFileFat := fmt.Sprintf("%s_%s-%s%s", artifact.Extra.Binary, artifact.Goos, artifact.Goarch, artifact.Extra.Ext)
			outPathFat := filepath.Join(outDir, outFileFat)
			err = CopyFile(fatFile, outPathFat)
			if err != nil {
				return fmt.Errorf("error copying files: %w", err)
			}
			log.Info().Str("Source", file).Str("Dest", outPathFat).Msg("moved fat artifact")
		} else {
			dllHeaderOutFile := fmt.Sprintf("%s_%s-%s%s", artifact.Extra.Binary, artifact.Goos, artifact.Goarch, artifact.Extra.Ext)
			dllHeaderOutPath := filepath.Join(outDir, dllHeaderOutFile)
			err = CopyFile(file, dllHeaderOutPath)
			if err != nil {
				log.Error().Err(err).Str("Source", file).Str("Dest", dllHeaderOutPath).Msg("error copying files")
			} else {
				log.Info().Str("Source", file).Str("Dest", dllHeaderOutPath).Msg("moved artifact")
			}
			if artifact.Extra.Ext == ".dll" {
				dllOutFile := fmt.Sprintf("%s_%s-%s%s", artifact.Extra.Binary, artifact.Goos, artifact.Goarch, ".h")
				dllOutPath := filepath.Join(outDir, dllOutFile)
				headerFile := strings.TrimSuffix(file, ".dll") + ".h"
				err = CopyFile(headerFile, dllOutPath)
				if err != nil {
					return fmt.Errorf("error copying header files: %w", err)
				}
				log.Info().Str("Source", file).Str("Dest", dllOutPath).Msg("moved header artifact")
			}
		}
	}

	return nil
}

func isFileSameSize(path1, path2 string) (bool, error) {
	f1, err := os.Stat(path1)
	if err != nil {
		return false, err
	}
	f2, err := os.Stat(path2)
	if err != nil {
		return false, err
	}
	sameSize := f1.Size() == f2.Size()

	return sameSize, nil
}
