version: 2

env:
  - APP_NAME=goa'uld
  - COMMON__ACCESS_TOKEN=

  - SERVER__AGE_PRIVKEY=
  - AGENT__AGE_PUBKEY=age1e4txlmjtmc4sx5f8s7fhpka64d4d05rj3qn3jy4tgrta4p22euvq00ac5p

  - HTTP_DOMAIN=www.example.com
  - TLS_DOMAIN=app.example.com
  - SSHD_PORT=2222
  - HTTP_PORT=80
  - HTTPS_PORT=443
  - AGENT__RSSH_ORDER=

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...


builds:
  - id: "server"
    mod_timestamp: "{{ .CommitTimestamp }}"
    binary: goauld_server
    main: ./server

    env:
      - CGO_ENABLED=0
      - SERVER__HTTP_DOMAIN={{ .Env.HTTP_DOMAIN }}
      - SERVER__TLS_DOMAIN={{ .Env.TLS_DOMAIN }}
      - SERVER__HTTP_PORT={{ .Env.HTTP_PORT }}
      - SERVER__HTTPS_PORT={{ .Env.HTTPS_PORT }}
      - SERVER__SSHD_PORT={{ .Env.SSHD_PORT }}
      # - CC=zig cc -target {{if eq .Arch "arm64"}}aarch64{{else if eq .Arch "arm"}}arm{{else if eq .Arch "amd64"}}x86_64{{else if eq .Arch "386"}}x86{{else}} RUNTIME.GOARCH{{end}}-{{ if eq .Os "darwin"}}macos-none -Wno-availability -Wno-nullability-completeness --sysroot=./scripts/build/MacOSX15.sdk/ -I./scripts/build/MacOSX15.sdk/usr/include -L./scripts/build/MacOSX15.sdk/usr/lib -F./scripts/build/MacOSX15.sdk/System/Library/Frameworks -framework CoreFoundation{{else if eq .Os "windows"}}windows-gnu{{else if eq .Os "linux"}}linux-musl{{else}}ERROR RUNTIME.GOOS{{end}}
      # - CXX=zig c++ -target {{if eq .Arch "arm64"}}aarch64{{else if eq .Arch "arm"}}arm{{else if eq .Arch "amd64"}}x86_64{{else if eq .Arch "386"}}x86{{else}} RUNTIME.GOARCH{{end}}-{{ if eq .Os "darwin"}}macos-none{{else if eq .Os "windows"}}windows-gnu{{else if eq .Os "linux"}}linux-musl{{else}}ERROR RUNTIME.GOOS{{end}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
#      - "386"
#      - arm
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -X Goauld/common.version={{.Version}} -X Goauld/common.commit={{.Commit}} -X Goauld/common.date={{.CommitDate}}
      - '{{ if (index .Env "SERVER__AGE_PRIVKEY") }} -X Goauld/server/config._age_privKey={{ .Env.SERVER__AGE_PRIVKEY }}{{end}}'

      - '{{ if (index .Env "SERVER__HTTP_DOMAIN") }} -X Goauld/server/config._http_domain={{ .Env.SERVER__HTTP_DOMAIN }}{{end}}'
      - '{{ if (index .Env "SERVER__TLS_DOMAIN") }} -X Goauld/server/config._tls_domain={{ .Env.SERVER__TLS_DOMAIN }}{{end}}'

      - '{{ if (index .Env "SERVER__HTTP_PORT") }} -X Goauld/server/config._http_port={{ .Env.SERVER__HTTP_PORT }}{{end}}'
      - '{{ if (index .Env "SERVER__HTTPS_PORT") }} -X Goauld/server/config._https_port={{ .Env.SERVER__HTTPS_PORT }}{{end}}'
      - '{{ if (index .Env "SERVER__SSHD_PORT") }} -X Goauld/server/config._sshd_port={{ .Env.SERVER__SSHD_PORT }}{{end}}'

      - '{{ if (index .Env "SERVER__VERBOSE") }} -X Goauld/server/config._verbosity={{ .Env.SERVER__VERBOSE }}{{end}}'
      - '{{ if (index .Env "SERVER__TLS") }} -X Goauld/server/config._tls={{ .Env.SERVER__TLS }}{{end}}'

      - '{{ if (index .Env "SERVER__NO_DB") }} -X Goauld/server/config._no_db={{ .Env.SERVER__NO_DB }}{{end}}'
      - '{{ if (index .Env "SERVER__DB_FILE_NAME") }} -X Goauld/server/config._db_name={{ .Env.SERVER__DB_FILE_NAME }}{{end}}'

      - '{{ if (index .Env "SERVER__ALLOWED_IPS") }} -X Goauld/server/config._allowed_ips={{ .Env.SERVER__ALLOWED_IPS }}{{end}}'
      - '{{ if (index .Env "COMMON__ACCESS_TOKEN") }} -X Goauld/server/config._access_token={{ .Env.COMMON__ACCESS_TOKEN }}{{end}}'
      - '{{ if (index .Env "SERVER__ADMIN_TOKEN") }} -X Goauld/server/config._admin_token={{ .Env.SERVER__ADMIN_TOKEN }}{{end}}'
      - "-s -w -buildid="
  - id: "agent"
    mod_timestamp: "{{ .CommitTimestamp }}"
    binary: goauld_agent
    main: ./agent
    env:
      - CGO_ENABLED=0
      - AGENT__SERVER={{ if (index .Env "HTTPS_PORT") }}https://{{ .Env.HTTP_DOMAIN }}:{{ .Env.HTTPS_PORT}}{{else}}https://{{ .Env.HTTP_DOMAIN }}:{{ .Env.HTTP_PORT}}{{end}}
      - AGENT__SSH_SERVER={{.Env.HTTP_DOMAIN}}:{{.Env.SSHD_PORT}}
      - AGENT__TLS_SERVER={{ if (and (index .Env "HTTPS_PORT") (index .Env "HTTPS_PORT")) }}{{.Env.TLS_DOMAIN}}:{{.Env.HTTPS_PORT}}{{end}}

    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -buildid=
      - -X Goauld/common.version={{.Version}} -X Goauld/common.commit={{.Commit}} -X Goauld/common.date={{.CommitDate}}
      - '{{ if (index .Env "AGENT__AGE_PUBKEY") }} -X Goauld/agent/config._agePubKey={{ .Env.AGENT__AGE_PUBKEY }}{{end}}'

      - '{{ if (index .Env "AGENT__LOCAL_SSH_PASSWORD") }} -X Goauld/agent/config._localSshPassword={{ .Env.AGENT__LOCAL_SSH_PASSWORD }}{{end}}'
      - '{{ if (index .Env "AGENT__NAME") }} -X Goauld/agent/config._name={{ .Env.AGENT__NAME }}{{end}}'

      - '{{ if (index .Env "AGENT__SSHD") }} -X Goauld/agent/config._sshd={{ .Env.AGENT__SSHD }}{{end}}'
      - '{{ if (index .Env "AGENT__SOCKS") }} -X Goauld/agent/config._socks={{ .Env.AGENT__SOCKS }}{{end}}'
      - '{{ if (index .Env "AGENT__SOCKS_PROXY") }} -X Goauld/agent/config._socks_use_system_proxy={{ .Env.AGENT__SOCKS_PROXY }}{{end}}'

      - '{{ if (index .Env "AGENT__SERVER") }} -X Goauld/agent/config._server={{ .Env.AGENT__SERVER }}{{end}}'
      - '{{ if (index .Env "AGENT__SSH_SERVER") }} -X Goauld/agent/config._ssh_server={{ .Env.AGENT__SSH_SERVER }}{{end}}'
      - '{{ if (index .Env "AGENT__TLS_SERVER") }} -X Goauld/agent/config._tls_server={{ .Env.AGENT__TLS_SERVER }}{{end}}'

      - '{{ if (index .Env "AGENT__RSSH_PORT") }} -X Goauld/agent/config._rssh_port={{ .Env.AGENT__RSSH_PORT }}{{end}}'
      - '{{ if (index .Env "AGENT__SOCKS_PORT") }} -X Goauld/agent/config._socks_port={{ .Env.AGENT__SOCKS_PORT }}{{end}}'

      - '{{ if (index .Env "AGENT__KEEPALIVE") }} -X Goauld/agent/config._keepalive={{ .Env.AGENT__KEEPALIVE }}{{end}}'
      - '{{ if (index .Env "AGENT__VERBOSE") }} -X Goauld/agent/config._verbosity={{ .Env.AGENT__VERBOSE }}{{end}}'

      - '{{ if (index .Env "AGENT__RSSH_ORDER") }} -X Goauld/agent/config._rssh_order={{ .Env.AGENT__RSSH_ORDER }}{{end}}'

      - '{{ if (index .Env "AGENT__RPF") }} -X Goauld/agent/config._remote_port_forwarding={{ .Env.AGENT__RPF }}{{end}}'

      - '{{ if (index .Env "AGENT__MAX_RETRIES") }} -X Goauld/agent/config._max_retries={{ .Env.AGENT__MAX_RETRIES }}{{end}}'

  - id: "client"
    mod_timestamp: "{{ .CommitTimestamp }}"
    binary: goauld_client
    main: ./client
    env:
      - CGO_ENABLED=0
      - CLIENT__SERVER={{ if (index .Env "HTTPS_PORT") }}https://{{ .Env.HTTP_DOMAIN }}:{{ .Env.HTTPS_PORT}}{{else}}https://{{ .Env.HTTP_DOMAIN }}:{{ .Env.HTTP_PORT}}{{end}}
      - CLIENT__SSH_SERVER={{.Env.HTTP_DOMAIN}}:{{.Env.SSHD_PORT}}

    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      # - "386"
      # - arm
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -buildid=
      - -X Goauld/common.version={{.Version}} -X Goauld/common.commit={{.Commit}} -X Goauld/common.date={{.CommitDate}}
      - '{{ if (index .Env "CLIENT__SERVER") }} -X main._server={{ .Env.CLIENT__SERVER }}{{end}}'
      - '{{ if (index .Env "CLIENT__SSH_SERVER") }} -X main._ssh_server={{ .Env.CLIENT__SSH_SERVER }}{{end}}'
      - '{{ if (index .Env "COMMON__ACCESS_TOKEN") }} -X main._access_token={{ .Env.COMMON__ACCESS_TOKEN }}{{end}}'

      - '{{ if (index .Env "CLIENT__VERBOSITY") }} -X main._verbosity={{ .Env.CLIENT__VERBOSITY }}{{end}}'
      - '{{ if (index .Env "CLIENT__INSECURE") }} -X main._insecure={{ .Env.CLIENT__INSECURE }}{{end}}'

      - '{{ if (index .Env "CLIENT__EXEC_SSH") }} -X main._exec_ssh={{ .Env.CLIENT__EXEC_SSH }}{{end}}'
      - '{{ if (index .Env "CLIENT__EXEC_SOCKS") }} -X main._exec_socks={{ .Env.CLIENT__EXEC_SOCKS }}{{end}}'
      - '{{ if (index .Env "CLIENT__EXEC_PRINT") }} -X main._exec_print={{ .Env.CLIENT__EXEC_PRINT }}{{end}}'
      - '{{ if (index .Env "CLIENT__EXEC_PROXY") }} -X main._exec_proxy={{ .Env.CLIENT__EXEC_PROXY }}{{end}}'

      - '{{ if (index .Env "CLIENT__LOCAL_SOCKS_PORT") }} -X main._local_socks_port={{ .Env.CLIENT__LOCAL_SOCKS_PORT }}{{end}}'
      - '{{ if (index .Env "CLIENT__LOCAL_SSHD_PORT") }} -X main._local_sshd_port={{ .Env.CLIENT__LOCAL_SSHD_PORT }}{{end}}'



# archives:
#   - formats: tar.gz
#     allow_different_binary_count: true
#     # this name template makes the OS and Arch compatible with the results of `uname`.
#     name_template: >-
#       {{ .ProjectName }}_
#       {{- title .Os }}_
#       {{- if eq .Arch "amd64" }}x86_64
#       {{- else if eq .Arch "386" }}i386
#       {{- else }}{{ .Arch }}{{ end }}
#       {{- if .Arm }}v{{ .Arm }}{{ end }}
#     # use zip for windows archives
#     format_overrides:
#       - goos: windows
#         formats: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
