services:
  goauld_server:
    build:
      context: .
    # platform: linux/amd64
    container_name: server
    image: goauld_server
    ports:
      - "X.X.X.X:53:53/tcp"
      - "X.X.X.X:53:53/udp"
      - "X.X.X.X:80:80"
      - "X.X.X.X:443:443"
      - "X.X.X.X:22222:22222"
    command: "[ -d /app/build_binaries ] && cp -u /app/build_binaries/* /app/binaries/ ; /app/server -c /app/server_config.yaml -vvv"
    volumes:
      - ./certmagic:/root/.local/share/certmagic
      - ./Goauld.db:/app/Goauld.db
      - ./server_config.yaml:/app/server_config.yaml
      - ./binaries:/app/binaries