#Age public key associated with the server. Must match the server’s public key.
age-pubkey: ""

# Control HTTP server to connect to.
server: www.example.com

# SSH server used for direct SSH connections.
ssh-server: www.example.com:22222

# QUIC domain used to tunnel traffic.
quic-domain: app.example.com

# TLS server used for SSH-over-TLS connections.
tls-server: app.example.com

# DNS servers used for SSH-over-DNS connections. Use 'system' to include the system DNS servers.
dns-server:
- tns.example.com
- 8.8.8.8
- 1.1.1.1
- 9.9.9.9

# DNS domain used to tunnel SSH-over-DNS traffic.
dns-domain: t.example.com

# DNS domain used to tunnel SSH-over-DNS traffic.
dns-domain-alt: s.example.com

# Password for local SSH access. If empty, a random password is generated automatically.
shared-password: ""

# Password required to access the agent.
password: ""

# Disable the local password generation if no static password is provided.
disable-password: false

# Friendly name to identify the agent (default: 'user@hostname').
name: user@hostname

# Enable the SSHD service.
sshd: true

# Enable the SOCKS proxy service.
socks: true

# Enable the HTTP proxy service.
http: true

# Enable the MITM HTTP proxy service.
mitm-http: false

# Enable the WireGuard service.
wg: false

# Enable the Relay service.
relay: false

# Username for the MITM HTTP upstream proxy.
mitm-http-proxy-username: ""

# Password for the MITM HTTP upstream proxy.
mitm-http-proxy-password: ""

# Domain for the MITM HTTP upstream proxy.
mitm-http-proxy-domain: ""

# Proxy URL to use for control server connections. If omitted, the system proxy is used (if configured).
proxy: ""

# Username for the proxy server.
proxy-username: ""

# Password for the proxy server.
proxy-password: ""

# Authentication domain for the proxy server.
proxy-domain: ""

# Custom proxy used within the SOCKS proxy. Falls back to the system proxy if not set.
socks-custom-proxy: ""

# Use the system proxy for all SOCKS proxy traffic.
socks-proxy: true

# Username for the SOCKS upstream proxy.
socks-proxy-username: ""

# Password for the SOCKS upstream proxy.
socks-proxy-password: ""

# Domain for the SOCKS upstream proxy.
socks-proxy-domain: ""

# Custom proxy used within the HTTP proxy. Falls back to the system proxy if not set.
http-custom-proxy: ""

# Username for the HTTP upstream proxy.
http-proxy-username: ""

# Password for the HTTP upstream proxy.
http-proxy-password: ""

# Domain for the HTTP upstream proxy.
http-proxy-domain: ""

# Ignore system proxy settings.
no-proxy: false

# Remote SSH port to bind on the server (0 = random).
rssh-port: 0

# Remote SOCKS proxy port to bind on the server (0 = random).
socks-port: 0

# Remote HTTP proxy port to bind on the server (0 = random).
http-port: 0

# Remote WireGuard port to bind on the server (0 = random).
wg-port: 0

# Remote WireGuard port to bind on the server (0 = random).
relay-port: 0

# Prevent the system from sleeping or locking.
keep-awake: false

# Interval in seconds between keepalive messages (0 = disabled).
keepalive: 20

# Increase log verbosity. Repeat for more detail.
verbose: 0

# Suppress all log output.
quiet: false

# Restrict agent activity to working days only.
only-working-days: false

# Start time of the working day (e.g. '09:00').
working-day-start: "8:00"

# End time of the working day (e.g. '17:00').
working-day-end: "19:30"

# Timezone used for working day calculations.
working-day-timezone: Europe/Paris

# Preferred order of SSH tunnel protocols.
rssh-order:
- SSH
- TLS
- WS
- HTTP
- DNS

# Timeout in seconds to wait for each SSH tunnel attempt (0 = unlimited).
ssh-timeout: 60

# Ports to forward to the server (REMOTE_PORT[:LOCAL_IP]:LOCAL_PORT). Use 0 for a random remote port.
rpf: []

# Maximum number of connection retries before giving up.
max-retries: 0

# Show version information and exit.
version: false

# Generate a configuration file from the current settings.
generate-config: false

# Path to the configuration file to use.
config-file: ""

# Run the agent in the background.
background: false

# Run the agent in hidden background mode.
hidden-background: false

# System command used to perform SSH over DNS when raw DNS queries are blocked. The provided command is responsible for performing the DNS query and returning the result as raw bytes.
#  Powershell example: "((Resolve-DnsName -Type TXT -Server 127.0.0.1 '%s')[0].Strings -join '' -replace '\s+', '' -split '..' | ForEach-Object { [Convert]::ToByte($_,16) } )"
#  Linux example:"dig +short +unknownformat -t TXT '%s' @127.0.0.1 | head -n1 | cut -d ' ' -f3- | tr -d ' '  | xxd -r -p".
custom-dns-command: ""

# Number of days before the agent self-terminates (0 = disabled).
kill-switch: 7

# Use another agent to relay the connection to the server.
relay-addr: ""

# Extra arguments that will be trashed, required when launching the agent in some contexts.
remaining: []

