# Access token required to access the /manage/ endpoint.
access-token: TODO_TOKEN

# Configuration file to use.
config-file: ""

# Allow insecure connection (do not validate TLS certificate).
insecure: false

# HTTP Server to connect to.
server: http://localhost

# SSH Server to connect to.
ssh-server: localhost:2222

# Verbosity. Repeat to increase
verbose: 0

