# Age private key to use.
age-privkey: 

# Domain used to serve HTTP content (HTTP/Websockets).
http-domain:
    - www.example.com

# Domain used to serve raw TLS content (SSH over TLS).
tls-domain:
    - app.example.com

# HTTP address to bind to, port 0 => Random.
http-listen-addr: :80

# HTTPS address to bind to, port 0 => Random.
https-listen-addr: :443

# Remote address to bind to, port 0 => Random.
ssh-listen-addr: :2222

# Verbosity. Repeat to increase
verbose: 0

# Enable TLS.
tls: true

# Path to TLS certificate key.
tls-key: ""

# Path to TLS certificate.
tls-cert: ""

# Disable database usage.
db: false

# Database filename to use.
db-file-name: Goauld.db

# List of IP allowed to access the /manage/ endpoint.
allowed-ips:
    - 127.0.0.1
    - 0.0.0.0/32

# Access token required to access the /manage/ endpoint.
access-token: TODO_TOKEN

# Access token required to access the /manage/ endpoint.
admin-token: TODO_TOKEN

# HTTP Basic Auth used to access the binaries endpoint.
binaries-basic-auth: username:password

# Path where are stored binaries on the filesystem.
binaries-path-location: ./binaries

# Generate configuration file based on the current options.
generate-config: false

# Configuration file to use.
config-file: ""

