# Access token required to access the /manage/ endpoint.
access-token: TODO_TOKEN

# Access token required to access the /manage/ endpoint.
admin-token: TODO_TOKEN

# Age private key to use.
age-privkey: 

# List of IP allowed to access the /manage/ endpoint.
allowed-ips:
  - 127.0.0.1
  - 0.0.0.0/32

# HTTP Basic Auth used to access the binaries endpoint.
binaries-basic-auth: M6FWvoAMszJV@5Zj5R9JugbpsieCE9qumDIv6UWLZbxjKKz2j

# Path where are stored binaries on the filesystem.
binaries-path-location: ./binaries

# Configuration file to use.
config-file: ""

# Disable database usage.
db: false

# Database filename to use.
db-file-name: Goauld.db

# Domain used to serve HTTP content (HTTP/Websockets).
http-domain: a.hazegard.fr

# HTTP port to bind to, 0 => Random.
http-port: 80

# HTTPS port to bind to, 0 => Random.
https-port: 443

# Remote port to bind to, 0 => Random.
ssh-port: 2222

# Enable TLS.
tls: true

# Path to TLS certificate.
tls-cert: ""

# Domain used to serve raw TLS content (SSH over TLS).
tls-domain: b.hazegard.fr

# Path to TLS certificate key.
tls-key: ""

# Verbosity. Repeat to increase
verbose: 0

